name: dadguide2
description: DadGuide v2

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Firebase plugins
  firebase_core: ^0.4.0
  firebase_admob: ^0.9.0+1
  firebase_analytics: ^3.0.2
  firebase_crashlytics: ^0.0.4+3
  firebase_performance: ^0.3.0
  firebase_remote_config: ^0.2.0+2
  cloud_firestore: ^0.12.1

  sqflite: ^1.1.0
  path_provider: ^1.1.0

  stack_trace: ^1.9.3
  # If updating this, need to verify cache.dart
  cached_network_image: 1.0.0
  protobuf: any

  # Database codegen
  moor_flutter: ^1.4.0

  # Injection
  provider: ^3.0.0+1

  # Settings page
  preferences: ^4.0.0

  # Date stuff
  intl: ^0.15.8

  # Http downloads
  dio: ^2.1.7

  # Logging
  flutter_fimber: ^0.3.0

  # More icons
  flutter_icons: ^0.1.4

  # Dependency injection
  get_it: ^1.0.3+2

  # Utilities
  quiver: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Database codegen
  moor_generator: ^1.4.0
  build_runner:

  flutter_launcher_icons: ^0.7.2

# To rebuild icons, use: flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/data/
  #  - images/a_dot_ham.jpeg
